#!/usr/bin/env bash
# Bash script to Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo chown -R ubuntu /etc/haproxy
sudo echo "
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 190577-web-01 18.204.7.165 check
        server 190577-web-02 18.207.2.94 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
